Changed handlers
denis1011101/super_cm_bot pull request #4
Opened 2024-10-01 20:46 UTC by GrayDog0

Changed top_ handlers, added unique comments to the display for the first ones in the list

2024-10-03 14:03 UTC, denis1011101 commented
мужики дисклеймер! хочется сильно не душнить и шоб была творческая атмосфера, так шо любиые предложения это бомба

2024-10-03 14:24 UTC, denis1011101 commented
Серёг давай переназовём имя пр'а и имя коммита, например `feature(tops): decoration tops`, либо что-то подобное

2024-10-03 14:25 UTC, denis1011101 commented on app/handlers/top_giga_handler.go
> -	"github.com/denis1011101/super_cm_bot/app"
Серёг давай вернём импорт, потому что ниже будем юзать функцию оттуда `app.SendMessage`

2024-10-03 14:28 UTC, denis1011101 commented on app/handlers/top_unhandsome_handler.go
> -	app.SendMessage(chatID, sb.String(), bot, update.Message.MessageID)
тут ты написал функцию заново, а лучше юзать [мою](https://github.com/GrayDog0/super_cm_bot/blob/main/app/bot.go#L10), это лаконичнее и приятнее)

2024-10-03 18:10 UTC, Keklil requested changes

2024-10-03 18:10 UTC, Keklil commented on app/handlers/top_giga_handler.go
> +	Data    string `db:"pen_name"`
Может подправить нейминг? Назначение с названием не сходится.
Зачем здесь теги?

2024-10-03 18:22 UTC, Keklil commented on app/handlers/top_giga_handler.go
> +	Data    string `db:"pen_name"`
Оо, это видимо отсылка к либе sqlx. Можем заюзать ее, тогда эти теги пригодятся

Вместо нашего цикла с rows.Next() будет такая крастота:
```
rows, err := sqlx.Select(db, &records, `
	SELECT pen_length, pen_name
	FROM pens 
	WHERE tg_chat_id = ? 
	ORDER BY pen_length DESC 
	LIMIT 10
`, chatID)
```

2024-10-03 18:27 UTC, Keklil submitted a review, later dismissed

2024-10-03 18:29 UTC, denis1011101 commented on app/handlers/top_unhandsome_handler.go
> +	uniqueComments := []string{"Самый крепкий анус на деревне 🐓", "Около пидорства 💩"}
Серёг там было больше словечек давай добавим остальные или если будут идеи какие-то свои, не ток в этом топе, во всех

2024-10-03 18:39 UTC, denis1011101 commented
такой 🤡, это Саня про себя ес шо, бывает!

2024-10-03 18:55 UTC, Keklil commented
Денис, не бань меня за это ревью, я реально клоун

2024-10-06 21:30 UTC, GrayDog0 commented on app/handlers/top_unhandsome_handler.go
> +	uniqueComments := []string{"Самый крепкий анус на деревне 🐓", "Около пидорства 💩"}
Я вроде вставил все слова из кода на пыхе, если есть идеи - пиши, добавлю.
Не знаешь, кстати какую-нибудь нейросетку годную, чтоб она придумала?
Можно хоть на каждого из списка отдельный комент записать

2024-10-06 21:33 UTC, GrayDog0 commented on app/handlers/top_giga_handler.go
> +	Data    string `db:"pen_name"`
@Keklil 

Изначально я учился как привязать значения из структры к запросу, но по итогу забил и просто поменял в запросе местами получаемые данные.
Добавить sqlx?

2024-10-06 21:35 UTC, GrayDog0 commented on app/handlers/top_unhandsome_handler.go
> -	app.SendMessage(chatID, sb.String(), bot, update.Message.MessageID)
Я написал заного из-за того, что не выходило по какой-то причине отправлять уникальные комменты с твоей функцией.

Ок, завтра заменю функцию и верну импорт "github.com/denis1011101/super_cm_bot/app"

2024-10-07 01:02 UTC, Keklil commented on app/handlers/top_giga_handler.go
> +	Data    string `db:"pen_name"`
Давай с sqlx попробуем, да
Либа уже заимпорчена даже, кажется

2024-10-07 20:12 UTC, denis1011101 commented on app/handlers/top_giga_handler.go
> +	Data    string `db:"pen_name"`
мужики я тут недавно сделал `go mod tidy` и неиспользуемые зависимости потёрлись, так шо надо будет снова добавить https://github.com/denis1011101/super_cm_bot/commit/43c6ad706f855b07c49da5c27d265943535d4281#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L15

2024-10-07 20:13 UTC, denis1011101 commented on app/handlers/top_unhandsome_handler.go
> +	uniqueComments := []string{"Самый крепкий анус на деревне 🐓", "Около пидорства 💩"}
идей пока нет, ща напишу какие ещё были

2024-10-07 20:21 UTC, denis1011101 commented on app/handlers/top_unhandsome_handler.go
> +	uniqueComments := []string{"Самый крепкий анус на деревне 🐓", "Около пидорства 💩"}
а вроде рил все

2024-10-07 20:26 UTC, denis1011101 commented on app/handlers/top_length_handler.go
> +	uniqueComments := []string{"Настоящий гигачад с елдой ", "Полупокер но с большим хреном ", "Лучше быть третьим чем выступать в цирке "}
во забыли одного
```php
            if ($idx === (count($penises) - 1)) {
                $text = '%s. @%s куколд с %s см 🤡';
            }
```

2024-10-07 20:33 UTC, denis1011101 commented on app/handlers/top_length_handler.go
> +	commonComment1 := " см 🤡"
считаю что имена переменных тут как фишка, шоб интереснее было код читать в будущем 😜

2024-10-08 22:52 UTC, merged